export interface AIService {
    suggestTaskDetails(input: string): Promise<{
        title: string;
        description?: string;
        dueDate?: Date;
        priority?: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
    }>;

    chat(message: string, context?: any): Promise<string>;
}

export class MockAIService implements AIService {
    async suggestTaskDetails(input: string) {
        // Simulate AI processing
        await new Promise((resolve) => setTimeout(resolve, 1000));

        const lowerInput = input.toLowerCase();
        let priority: "LOW" | "MEDIUM" | "HIGH" | "URGENT" = "MEDIUM";

        if (lowerInput.includes("urgente") || lowerInput.includes("asap")) {
            priority = "URGENT";
        } else if (lowerInput.includes("importante")) {
            priority = "HIGH";
        }

        let dueDate = undefined;
        if (lowerInput.includes("mañana")) {
            const tomorrow = new Date();
            tomorrow.setDate(tomorrow.getDate() + 1);
            dueDate = tomorrow;
        } else if (lowerInput.includes("hoy")) {
            dueDate = new Date();
        }

        return {
            title: input,
            description: "Generated by Ordo AI based on your input.",
            priority,
            dueDate,
        };
    }

    async chat(message: string, context?: any) {
        await new Promise((resolve) => setTimeout(resolve, 1000));
        return `I am Ordo AI. You said: "${message}". I am currently in development mode.`;
    }
}

export const aiService = new MockAIService();
