import { UseCase } from '../../shared/use-case';
import { ActivityRepository, CreateActivityInput } from '../provider/activity.repository';
import { Activity } from '../model/activity.entity';

export interface LogActivityInput extends CreateActivityInput {}

export class LogActivityUseCase implements UseCase<LogActivityInput, Activity> {
  constructor(private readonly activityRepo: ActivityRepository) {}

  async execute(input: LogActivityInput): Promise<Activity> {
    // Create activity entity (in draft mode since we don't have ID yet)
    const activity = new Activity({
      id: '', // Will be generated by repository
      taskId: input.taskId,
      userId: input.userId,
      type: input.type,
      metadata: input.metadata,
      createdAt: new Date(),
    });

    // Save to repository
    return await this.activityRepo.logActivity(input);
  }
}
